apiVersion: v2
name: kube-argus
description: A production-grade Kubernetes dashboard for SREs and platform engineers
type: application
version: 0.2.0
appVersion: "1.1.0"
keywords:
  - kubernetes
  - dashboard
  - monitoring
  - sre
home: https://github.com/manishchaudhary101/kube-argus
sources:
  - https://github.com/manishchaudhary101/kube-argus
